- name: Eliminar una instancia de AWS
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:


   - name: Terminate every running instance in a region. Use with EXTREME caution.
     amazon.aws.ec2_instance:
       state: absent
       filters:
         instance_ids: "{{ instance_id }}"
       register: ec2

   - name: Recolectar informacion de la instancia
     ansible.builtin.debug:
       msg: "El mensaje de salida es {{ ec2 }}"
