- name: Eliminar una instancia de AWS
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

   - name: Eliminar una instancia en particular por ID
     amazon.aws.ec2_instance:
       state: absent
       instance_ids:
         - "{{ instance_id }}"
       register: ec2

   - name: Recolectar informacion de la instancia
     ansible.builtin.debug:
       msg: "El mensaje de salida es {{ ec2 }}"
