- name: Eliminar una instancia de AWS
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - instance_name: nombredelainstacia 
  tasks:
    
   - name: "Eliminar la instacia llamada {{ instance_name }}"
     amazon.aws.ec2_instance:
       state: absent
       filters:
         tag:Name: "{{ instance_name }}"
    register: ec2

   - name: Recolectar informacion de la instancia
     ansible.builtin.debug:
       msg: "El mensaje de salida es {{ ec2 }}"
