- name: Aplicación de parches en windows server
  hosts: all
  tasks:
    - name: Comprobar si faltan actualizaciones
      ansible.windows.win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        state: searched
        log_path: C:\Windows\Temp\Pre-AllUpdatesFound.txt
      register: update_results

    - name: Informe de resultados actualizados
      debug:
        var: update_results


#    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
#      ansible.windows.win_updates:
#        category_names: SecurityUpdates
#        state: searched
#        log_path: C:\ansible_wu.txt
#      register: update_results1
#
#    - name: Informe de resultados actualizados
#      debug:
#        var: update_results1
        
#    - name: Informe de resultados actualizados
#      debug:
#        msg: |
#          {% for k in update_results.updates %}
#          {{ update_results.updates[k].title }}
#          {% endfor %}
