---
- name: Windows Users
  hosts: all
  
  tasks:
    - name: Crear grupo local para contener nuevos usuarios
      ansible.windows.win_group:
        name: LocalGroup
        description: Allow access to C:\Development folder

    - name:  Crear usuario local
      win_user:
        name: '{{ item.name }}'
        password: '{{ item.password }}'
        groups: LocalGroup
        update_password: no
        password_never_expires: yes
      loop:
      - name: ansible01
        password: Password123.

    - name: Crear carpeta Development
      ansible.windows.win_user:
        path: C:\Development
        state: directory
