---
- name: Playbook para crear backup de una maquina Linux
  hosts: all
  vars:
    mysql_root_password: ABCde123.
    mysql_username: root
    db_name: 
  tasks:

  - name: Crear la carpeta /var/backup en la maquina local
    ansible.builtin.file:
      path: /var/backup
      state: directory
      mode: '0777'


  - name: mysqldump
    ansible.builtin.shell: mysqldump -u {{ mysql_username }} -p{{ mysql_root_password }} {{ db_name }} > /var/backup/{{ db_name }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.sql
