---
- name: Instalacion y alistamineto de un servidor web apache
  hosts: all
  gather_facts: false
  vars:
    ambiente: prod
  tasks:

  - name: Poner contenido en el servidor web apache
    ansible.builtin.template:
      src: j2/ascii-{{ ambiente }}.html.j2
      dest: /var/www/html/index.html


  - name: 6. Probar que el servicio este funcionando
    ansible.builtin.uri:
      url: "http://{{ ansible_host}}"

  - name: 7. Mostrar el URL
    ansible.builtin.debug:
      msg: "http://{{ ansible_host}}"
