---
- name: Comprimir y mover archivos de logs en /var/log/httpd
  hosts: all
  tasks:
    - name: Comprimir archivos de logs
      archive:
        path: /var/log/httpd/
        dest: /tmp/logs_comprimidos.tar.gz
        format: gz
        exclude_path: "*.log"


    - name: Buscar archivos para eliminarlos 
      find:
        paths: /var/log/httpd/
        patterns: "*.log"
        use_regex: true
        file_type: directory
      register: folders_to_delete

    - name: Mostrar los archivos a Borrar
      debug:
        var: folders_to_delete

    - name: Elimiar archivos
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ folders_to_delete.files }}"
